---
title: Adityo Pratama
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Fullstack Software Engineer
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
